import { DeterministicRng } from './core/deterministic-rng.js';
import { DECISION_SLICE_SECONDS, HALF_SECONDS, FULL_TIME_SECONDS, SimulationClock } from './core/simulation-clock.js';
import { normalizeMatchPlayer, contextualSkill } from './core/player-attributes.js';
import { createBallState, attachBall, launchBall, updateBallFlight } from './core/ball-state.js';
import { FORMATIONS, FORMATION_NAMES, getFormation, slotGroup } from './tactics/formations.js';
import { PLAYER_ROLE_OPTIONS, canonicalRole, defaultRoleForSlot, roleFamiliarity } from './tactics/role-catalog.js';
import { DEFAULT_TACTICS, normalizeTeamInstructions } from './tactics/team-instructions.js';
import { tacticalAnchor, tacticalShapeSnapshot } from './tactics/tactical-shapes.js';
import { decide } from './decisions/decision-engine.js';
import { planPass } from './actions/passing.js';
import { resolveReception } from './actions/receiving.js';
import { resolveCarry } from './actions/carrying.js';
import { planShot } from './actions/shooting.js';
import { goalkeeperAnchor } from './actions/goalkeeping.js';
import { drainEnergy, activityFor } from './physical/energy.js';
import { maybeInjure } from './physical/injuries.js';
import { competitionRules } from './rules/competition-rules.js';
import { canQueueSubstitution, registerSubstitution } from './rules/substitutions.js';
import { evaluateOffside } from './rules/offside.js';
import { createReferee, evaluateChallenge } from './rules/referee.js';
import { createTeamStats, createPlayerStats, tacticalMetrics, updateTerritory } from './analytics/match-analytics.js';
import { finalizeRatings } from './analytics/player-ratings.js';
import { observeMatch } from './manager/tactical-observer.js';
import { managerDecision } from './manager/manager-policy.js';
import { ReplayBuffer } from './presentation/replay-buffer.js';
import { resolveCorner } from './set-pieces/set-piece-engine.js';
import { localPoint, worldPoint, metricDistance, clamp01, inPenaltyArea } from './spatial/pitch-model.js';

export const SIMULATION_VERSION='touchline-match-sim-v3';
export { DECISION_SLICE_SECONDS, HALF_SECONDS, FULL_TIME_SECONDS, FORMATIONS, FORMATION_NAMES, PLAYER_ROLE_OPTIONS, DEFAULT_TACTICS };
export const MAX_SUBSTITUTIONS=5; export const MAX_SUBSTITUTION_WINDOWS=3;
const EPS=1e-8; const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0)); const same=(a,b)=>String(a)===String(b); const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;

function findRaw(team,id){return (team?.squad||[]).find(p=>same(p.id,id))||null}
function lineupRaw(team,lineup){const rows=(lineup||[]).map(x=>typeof x==='object'?x:findRaw(team,x)).filter(Boolean);if(rows.length>=11)return rows.slice(0,11);const rest=(team?.squad||[]).filter(p=>!rows.some(r=>same(r.id,p.id))).sort((a,b)=>(Number(b.overall??b.rating)||0)-(Number(a.overall??a.rating)||0));return [...rows,...rest].slice(0,11)}
function playerState(raw,slot,index,tactics,direction){const p=normalizeMatchPlayer(raw);const specified=tactics.playerRoles?.[String(p.id)];const instruction=canonicalRole(specified||defaultRoleForSlot(slot.role),slot.role);const fit=roleFamiliarity(p,instruction,slot.role);const w=worldPoint({direction},{x:slot.x,y:slot.y});return {id:p.id,player:p,slotIndex:index,role:slot.role,instructionRole:instruction,tacticalFit:fit,positionZoneFit:1,x:w.x,y:w.y,targetX:w.x,targetY:w.y,velocityX:0,velocityY:0,stamina:clamp(p.condition,1,100),matchLoad:0,currentActivity:'walk',yellowCards:0,redCard:false,injured:null,intention:null,lastDecisionEvidence:null,stats:createPlayerStats()}}
function makeTeam(team,lineup,tacticInput,direction){const tactics=normalizeTeamInstructions(tacticInput);const raw=lineupRaw(team,lineup);const shape=getFormation(tactics.formation);const players=raw.map((p,i)=>playerState(p,shape[i]||shape.at(-1),i,tactics,direction));const ids=new Set(players.map(p=>String(p.id)));const bench=(team?.squad||[]).filter(p=>!ids.has(String(p.id))).map(p=>normalizeMatchPlayer(p));return {team,direction,tactics,pendingTactics:null,players,bench,stats:createTeamStats(),usedPlayerIds:[...ids],substitutedOutIds:[],substitutionHistory:[],substitutionsUsed:0,substitutionWindowsUsed:0,pendingSubstitution:null,ai:{enabled:false,lastDecisionAt:-999,lastSubMinute:-999,lastTacticalMinute:-999},profile:null}}
function setCarrier(state,teamIndex,player){state.possessionTeamIndex=teamIndex;attachBall(state.ball,player,teamIndex);state.activeAction=null}
function closest(team,point,filter=()=>true){return team.players.filter(p=>!p.redCard&&filter(p)).sort((a,b)=>metricDistance(a,point)-metricDistance(b,point))[0]||null}
function minute(state){return Math.min(130,Math.floor(state.clockSeconds/60)+1)}

export function sanitizePlayerPosition(position,role,base={x:.5,y:.5}){const group=slotGroup(role);const lim=group==='GK'?{x:[.02,.22],y:[.3,.7]}:group==='DEF'?{x:[.08,.62],y:[.03,.97]}:group==='FWD'?{x:[.38,.97],y:[.02,.98]}:{x:[.18,.88],y:[.04,.96]};const x=clamp(position?.x??base.x,lim.x[0],lim.x[1]),y=clamp(position?.y??base.y,lim.y[0],lim.y[1]);const d=Math.hypot(x-base.x,y-base.y);return {x,y,zoneFit:clamp(1-d*.45,.72,1),displacement:d,clamped:Math.abs(x-(position?.x??base.x))>EPS||Math.abs(y-(position?.y??base.y))>EPS}}
export function calculateTeamProfile(team,lineup,tacticsInput={}){const raw=lineupRaw(team,lineup),t=normalizeTeamInstructions(tacticsInput);const ratings=raw.map(p=>Number(p.overall??p.rating)||70);const attrs=raw.map(p=>normalizeMatchPlayer(p).attributes);return {overall:Math.round(avg(ratings)),technique:Math.round(avg(attrs.map(a=>(a.technique+a.passing+a.firstTouch)/3))),physical:Math.round(avg(attrs.map(a=>(a.pace+a.stamina+a.strength)/3))),defending:Math.round(avg(attrs.map(a=>(a.defending+a.positioning+a.tackling)/3))),cohesion:90,customPositions:Object.keys(t.playerPositions||{}).length,roleFit:92,attackIntent:Math.round(t.mentality*.55+t.tempo*.25+t.passingRisk*.2),pressIntensity:Math.round(clamp(t.pressing+(t.counterpress?10:0),0,100))}}

export class MatchEngine{
 constructor({home,away,homeLineup,awayLineup,homeTactics,awayTactics,seed=1,realDurationSeconds=120,aiTeamIndexes=[],strictInvariants=false,requiresWinner=false,rules=null}={}){if(!home||!away)throw new TypeError('MatchEngine requires home and away teams.');this.listeners=new Set();this.rng=new DeterministicRng(seed);this.clock=new SimulationClock({realDurationSeconds});this.rules=competitionRules(rules||{requiresWinner});this.strictInvariants=Boolean(strictInvariants);this.eventId=0;this.nextDecisionAt=2.5;this.referee=createReferee((this.rng.next()-.5)*.5);this.replay=new ReplayBuffer();this.state={version:SIMULATION_VERSION,seed,phase:'prematch',period:1,paused:true,speed:1,clockSeconds:0,halftimeCompleted:false,score:[0,0],events:[],possessionTeamIndex:this.rng.chance(.5)?0:1,lastPossessionChangeAt:0,lastCompletedPass:null,stoppage:null,shootout:null,activeAction:null,spatial:{pressure:{},tactical:[]},analytics:{tactical:[],insights:[[],[]]},teams:[makeTeam(home,homeLineup,homeTactics,1),makeTeam(away,awayLineup,awayTactics,-1)],ball:createBallState()};this.state.teams.forEach((t,i)=>{t.ai.enabled=aiTeamIndexes.includes(i);t.profile=calculateTeamProfile(t.team,t.players.map(p=>p.id),t.tactics)});this.resetKickoff(this.state.possessionTeamIndex);this.refreshDerived()}
 subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)} notify(type,payload={}){for(const fn of this.listeners)fn({type,payload,snapshot:this.state})} getSnapshot(){return this.state}
 addEvent(type,teamIndex,playerId,description,extra={}){const e={id:++this.eventId,type,teamIndex,playerId,minute:minute(this.state),second:Math.floor(this.state.clockSeconds),description,...extra};this.state.events.unshift(e);if(this.state.events.length>800)this.state.events.length=800;this.notify('event',{event:e});return e}
 start(){if(this.state.phase==='prematch'){this.state.phase='firstHalf';this.state.paused=false;this.addEvent('kickoff',null,null,'A partida começou.');return true}if(this.state.phase==='halftime')return this.resumeSecondHalf();if(this.state.phase==='extraTimeBreak')return this.resumeExtraTime();return false}
 setPaused(v){if(this.state.phase==='fulltime')return false;if(!v&&this.state.phase==='halftime')return this.resumeSecondHalf();this.state.paused=Boolean(v);this.notify('pause',{paused:this.state.paused});return true}
 setSpeed(v){this.state.speed=this.clock.setSpeed(v);this.notify('speed',{speed:this.state.speed});return this.state.speed}
 resumeSecondHalf(){if(this.state.phase!=='halftime')return false;this.applyPendingChanges({halftime:true});this.state.halftimeCompleted=true;this.state.period=2;this.state.phase='secondHalf';this.state.paused=false;this.resetKickoff(1);this.nextDecisionAt=this.state.clockSeconds+2.2;this.addEvent('secondHalf',null,null,'Começa o segundo tempo.');return true}
 resumeFromHalftime(){return this.resumeSecondHalf()}
 resumeExtraTime(){if(this.state.phase!=='extraTimeBreak')return false;this.state.phase='extraTime';this.state.paused=false;this.state.period=3;this.resetKickoff(0);this.addEvent('extraTime',null,null,'Começa a prorrogação.');return true}
 queueTactics(teamIndex,patch,options={}){const team=this.state.teams[teamIndex];if(!team)return {ok:false,reason:'Equipe inválida.'};team.pendingTactics=normalizeTeamInstructions({...team.tactics,...patch});this.addEvent('tacticalChange',teamIndex,null,'Mudança tática preparada para a próxima interrupção.',{source:options.source||'user',status:'queued'});return {ok:true}}
 previewPlayerPosition(teamIndex,playerId,position,formationName=null){const team=this.state.teams[teamIndex],p=team?.players.find(x=>same(x.id,playerId));if(!p)return null;const shape=getFormation(formationName||team.pendingTactics?.formation||team.tactics.formation),slot=shape[p.slotIndex]||shape.at(-1),v=sanitizePlayerPosition(position,slot.role,slot);return {...v,role:slot.role,playerId:p.id,tacticalFit:roleFamiliarity(p.player,p.instructionRole,slot.role)*v.zoneFit}}
 queueSubstitution(teamIndex,outgoingId,incomingId,options={}){const team=this.state.teams[teamIndex];if(!team)return {ok:false,reason:'Equipe inválida.'};const out=team.players.find(p=>same(p.id,outgoingId)),incoming=team.bench.find(p=>same(p.id,incomingId));if(!out||!incoming)return {ok:false,reason:'Jogadores inválidos.'};if(out.redCard)return {ok:false,reason:'Um atleta expulso não pode ser substituído.'};if(team.pendingSubstitution)return {ok:false,reason:'Já existe uma substituição preparada.'};const allowed=canQueueSubstitution(team,this.rules,{halftime:this.state.phase==='halftime'});if(!allowed.ok)return allowed;team.pendingSubstitution={outgoingId,incomingId,source:options.source||'user',queuedAt:this.state.clockSeconds};this.addEvent('substitutionPrepared',teamIndex,outgoingId,`${incoming.name} está pronto para entrar.`);return {ok:true}}
 applyPendingChanges(options={}){this.state.teams.forEach((t,i)=>{this.applyTeamTactics(t,i);this.applyTeamSubstitution(t,i,options)})}
 applyTeamTactics(team,teamIndex){if(!team.pendingTactics)return;team.tactics=team.pendingTactics;team.pendingTactics=null;const shape=getFormation(team.tactics.formation);team.players.forEach((p,i)=>{const slot=shape[i]||shape.at(-1);p.role=slot.role;p.instructionRole=canonicalRole(team.tactics.playerRoles?.[String(p.id)]||p.instructionRole,slot.role);p.tacticalFit=roleFamiliarity(p.player,p.instructionRole,slot.role)});team.profile=calculateTeamProfile(team.team,team.players.map(p=>p.id),team.tactics);this.addEvent('tacticalChange',teamIndex,null,`Estrutura alterada para ${team.tactics.formation}.`,{status:'applied'})}
 applyTeamSubstitution(team,teamIndex,{halftime=false}={}){const q=team.pendingSubstitution;if(!q)return;team.pendingSubstitution=null;const oi=team.players.findIndex(p=>same(p.id,q.outgoingId)),bi=team.bench.findIndex(p=>same(p.id,q.incomingId));if(oi<0||bi<0)return;const out=team.players[oi],raw=team.bench[bi],shape=getFormation(team.tactics.formation),slot=shape[oi]||shape.at(-1),replacement=playerState(raw,slot,oi,team.tactics,team.direction);replacement.x=out.x;replacement.y=out.y;out.stats.subbedOut=true;out.stats.minuteOut=minute(this.state);team.players[oi]=replacement;team.bench.splice(bi,1);registerSubstitution(team,this.rules,{halftime});team.usedPlayerIds.push(String(raw.id));team.substitutedOutIds.push(String(out.id));team.substitutionHistory.push({minute:minute(this.state),outgoingId:out.id,incomingId:raw.id,source:q.source});if(same(this.state.ball.carrierId,out.id))setCarrier(this.state,teamIndex,replacement);this.addEvent('substitution',teamIndex,replacement.id,`${raw.name} entrou no lugar de ${out.player.name}.`,{outgoingId:out.id,incomingId:raw.id,source:q.source})}
 resetKickoff(teamIndex){const team=this.state.teams[teamIndex],p=team.players.find(x=>['ST','RST','LST','AM'].includes(x.role)&&!x.redCard)||team.players.find(x=>!x.redCard);if(p){p.x=.5;p.y=.5}setCarrier(this.state,teamIndex,p)}
 tick(realDelta){if(this.state.paused||['prematch','halftime','extraTimeBreak','fulltime'].includes(this.state.phase))return;this.clock.pushRealDelta(realDelta);let guard=0;while(this.clock.canConsume()&&!this.state.paused&&guard++<1024)this.processSlice(this.clock.consume());if(guard>=1024)throw new Error('Simulation slice guard exceeded');if(this.strictInvariants){const c=this.checkInvariants();if(!c.ok)throw new Error(c.errors.join(' | '))}}
 processGameWindow(seconds){let left=Math.max(0,Number(seconds)||0);while(left>EPS&&!this.state.paused&&this.state.phase!=='fulltime'){const dt=Math.min(DECISION_SLICE_SECONDS,left);this.processSlice(dt);left-=dt}}
 processSlice(dt){const s=this.state;let end=s.phase==='firstHalf'?HALF_SECONDS:s.phase==='secondHalf'?FULL_TIME_SECONDS:s.phase==='extraTime'?FULL_TIME_SECONDS+30*60:FULL_TIME_SECONDS;const usable=Math.min(dt,end-s.clockSeconds);if(usable<=EPS){this.periodBoundary();return}s.clockSeconds+=usable;s.teams[s.possessionTeamIndex].stats.possessionSeconds+=usable;this.movePlayers(usable);this.updateEnergy(usable);const arrival=updateBallFlight(s.ball,usable);if(arrival.arrived)this.resolveBallArrival(arrival.action);if(!s.ball.action&&s.ball.carrierId&&s.clockSeconds>=this.nextDecisionAt)this.resolveDecision();this.maybeManageAi();if(Math.floor(s.clockSeconds*4)%4===0)this.refreshDerived();this.replay.push(this.presentationSnapshot());if(s.clockSeconds+EPS>=end)this.periodBoundary()}
 movePlayers(dt){const s=this.state;s.teams.forEach((team,ti)=>team.players.forEach(p=>{if(p.redCard)return;let anchor=p.role==='GK'?goalkeeperAnchor(team,p,s.ball):tacticalAnchor(s,ti,p);p.targetX=anchor.x;p.targetY=anchor.y;const pace=contextualSkill(p,['pace','acceleration','stamina'])/100;const maxMove=dt*(.016+.025*pace);const dx=anchor.x-p.x,dy=anchor.y-p.y,d=Math.hypot(dx,dy);if(d>EPS){const scale=Math.min(1,maxMove/d);p.velocityX=dx/d*maxMove/dt;p.velocityY=dy/d*maxMove/dt;p.x=clamp01(p.x+dx*scale);p.y=clamp01(p.y+dy*scale);p.stats.distanceKm+=metricDistance({x:p.x-dx*scale,y:p.y-dy*scale},p)/1000;if(Math.hypot(p.velocityX,p.velocityY)>.025){p.stats.sprints+=dt/8;team.stats.sprints+=dt/8}}}));if(s.ball.carrierId){const p=s.teams.flatMap(t=>t.players).find(x=>same(x.id,s.ball.carrierId));if(p){s.ball.x=p.x;s.ball.y=p.y;s.ball.z=0}}}
 updateEnergy(dt){this.state.teams.forEach((team,ti)=>team.players.forEach(p=>{if(p.redCard)return;const activity=activityFor(p,this.state,ti);p.currentActivity=activity;drainEnergy(p,dt,activity,team.tactics);p.stats.minutes+=dt/60;maybeInjure(p,this.rng,{activity})}))}
 resolveDecision(){const s=this.state,ti=s.possessionTeamIndex,team=s.teams[ti];let p=team.players.find(x=>same(x.id,s.ball.carrierId)&&!x.redCard);if(!p){p=closest(team,s.ball);if(p)setCarrier(s,ti,p);else return}p.stats.touches++;updateTerritory(s,ti,p);const d=decide(s,ti,p,this.rng);p.intention=d.choice.type;p.lastDecisionEvidence=d.evidence;const c=d.choice;if(c.type==='shot')this.startShot(ti,p);else if(['pass','throughPass','longPass'].includes(c.type))this.startPass(ti,p,c.target,c.type);else this.doCarry(ti,p,c.type==='dribble');this.nextDecisionAt=s.clockSeconds+this.rng.range(2.1,4.8)*(1.15-team.tactics.tempo/220)}
 startPass(ti,p,target,type){if(!target)return this.doCarry(ti,p,false);const off=evaluateOffside(this.state,ti,target,{...this.state.ball});if(off.offside){this.state.teams[ti].stats.offsides++;target.stats.offsides++;this.addEvent('offside',ti,target.id,`Impedimento de ${target.player.name}.`);this.changePossession(1-ti,closest(this.state.teams[1-ti],target));this.stoppage('offside');return}const plan=planPass(this.state,ti,p,target,type,this.rng),team=this.state.teams[ti];team.stats.passesAttempted++;p.stats.passesAttempted++;this.state.activeAction=plan;launchBall(this.state.ball,{from:p,to:plan.to,duration:plan.duration,height:plan.height,type:'pass',targetId:plan.targetId,teamIndex:ti,playerId:p.id,outcome:plan})}
 resolveBallArrival(action){const s=this.state,plan=action.outcome;if(!plan){s.ball.action=null;return}if(plan.kind==='pass'){const ti=s.ball.lastTouchTeamIndex,receiverTeam=plan.receiverTeamIndex;if(receiverTeam==null){const winner=closest(s.teams[1-ti],s.ball);this.changePossession(1-ti,winner);return}const receiver=s.teams[receiverTeam]?.players.find(p=>same(p.id,plan.receiverId));if(!receiver){this.changePossession(1-ti,closest(s.teams[1-ti],s.ball));return}if(receiverTeam===ti){const rec=resolveReception(s,ti,receiver,this.rng,{passQuality:plan.success});if(rec.success){const passer=s.teams[ti].players.find(p=>same(p.id,plan.passerId));s.teams[ti].stats.passesCompleted++;if(passer)passer.stats.passesCompleted++;if(plan.progress>.12){s.teams[ti].stats.progressivePasses++;if(passer)passer.stats.progressivePasses++}s.lastCompletedPass={teamIndex:ti,passerId:plan.passerId,receiverId:receiver.id,at:s.clockSeconds};setCarrier(s,ti,receiver)}else this.changePossession(1-ti,closest(s.teams[1-ti],receiver))}else{receiver.stats.interceptions++;s.teams[receiverTeam].stats.interceptions++;this.changePossession(receiverTeam,receiver)}}else if(plan.kind==='shot')this.finishShot(plan);s.ball.action=null;s.activeAction=null}
 doCarry(ti,p,dribble){const r=resolveCarry(this.state,ti,p,this.rng,{dribble});if(r.success){p.x=r.to.x;p.y=r.to.y;attachBall(this.state.ball,p,ti);if(dribble&&r.defender){p.stats.duels++;p.stats.duelsWon++;r.defender.stats.duels++}}else{p.stats.duels++;if(r.winner){r.winner.stats.duels++;r.winner.stats.duelsWon++;this.state.teams[1-ti].stats.tackles++;r.winner.stats.tackles++;const incident=evaluateChallenge({defender:r.winner,attacker:p,duel:r.duel,referee:this.referee,rng:this.rng,inBox:inPenaltyArea(this.state.teams[ti],p)});if(incident.foul)return this.handleFoul(1-ti,r.winner,p,incident)}this.changePossession(1-ti,r.winner||closest(this.state.teams[1-ti],p))}}
 startShot(ti,p){const plan=planShot(this.state,ti,p,this.rng),team=this.state.teams[ti];team.stats.shots++;team.stats.xG+=plan.xG;p.stats.shots++;p.stats.xG+=plan.xG;if(plan.onTarget){team.stats.shotsOnTarget++;p.stats.shotsOnTarget++}this.state.activeAction=plan;launchBall(this.state.ball,{from:p,to:plan.to,duration:plan.duration,height:plan.height,type:'shot',teamIndex:ti,playerId:p.id,outcome:{...plan,teamIndex:ti}})}
 finishShot(plan){const s=this.state,ti=plan.teamIndex,team=s.teams[ti],opp=s.teams[1-ti],shooter=team.players.find(p=>same(p.id,plan.shooterId)),gk=opp.players.find(p=>same(p.id,plan.goalkeeperId));if(plan.goal){team.stats.goals++;s.score[ti]++;if(shooter)shooter.stats.goals++;const pass=s.lastCompletedPass,assist=pass?.teamIndex===ti&&s.clockSeconds-pass.at<12?team.players.find(p=>same(p.id,pass.passerId)):null;if(assist&&!same(assist.id,shooter?.id)){assist.stats.assists++;team.stats.keyPasses++;assist.stats.keyPasses++}const e=this.addEvent('goal',ti,shooter?.id||null,`Gol de ${shooter?.player.name||'Touchline'}.`,{xG:plan.xG,assistPlayerId:assist?.id||null});e.replay=this.replay.capture(e);this.stoppage('goal');this.resetKickoff(1-ti);return}if(plan.onTarget){if(gk){gk.stats.saves++;opp.stats.saves++}this.addEvent('shotOnTarget',ti,shooter?.id||null,`${shooter?.player.name||'Finalização'} obrigou o goleiro a trabalhar.`,{xG:plan.xG});if(this.rng.chance(.18)){team.stats.corners++;const corner=resolveCorner(s,ti,this.rng);this.addEvent('corner',ti,corner.taker?.id||null,'Escanteio.',{setPiece:corner});if(corner.won&&corner.attacker&&this.rng.chance(corner.xG)){team.stats.goals++;s.score[ti]++;corner.attacker.stats.goals++;this.addEvent('goal',ti,corner.attacker.id,`Gol de ${corner.attacker.player.name} após escanteio.`,{xG:corner.xG,setPiece:'corner'});this.resetKickoff(1-ti)}else this.changePossession(1-ti,gk||closest(opp,s.ball))}else this.changePossession(1-ti,gk||closest(opp,s.ball))}else{this.addEvent('shot',ti,shooter?.id||null,`${shooter?.player.name||'Jogador'} finalizou para fora.`,{xG:plan.xG});this.changePossession(1-ti,gk||closest(opp,s.ball))}this.stoppage('shot')}
 handleFoul(defTeamIndex,defender,attacker,incident){const team=this.state.teams[defTeamIndex];team.stats.fouls++;defender.stats.fouls++;if(incident.yellow){defender.yellowCards++;team.stats.yellowCards++;this.addEvent('yellowCard',defTeamIndex,defender.id,`Cartão amarelo para ${defender.player.name}.`);if(defender.yellowCards>=2)incident.red=true}if(incident.red){defender.redCard=true;team.stats.redCards++;this.addEvent('redCard',defTeamIndex,defender.id,`${defender.player.name} foi expulso.`)}if(incident.penalty){const atk=1-defTeamIndex,taker=this.state.teams[atk].players.filter(p=>!p.redCard).sort((a,b)=>contextualSkill(b,['penalties','finishing','composure'])-contextualSkill(a,['penalties','finishing','composure']))[0];const goal=this.rng.chance(clamp(.72+(contextualSkill(taker,['penalties','composure'])-75)/240,.55,.9));this.addEvent('penalty',atk,taker?.id||null,'Pênalti marcado.');if(goal){this.state.score[atk]++;this.state.teams[atk].stats.goals++;if(taker)taker.stats.goals++;this.addEvent('goal',atk,taker?.id||null,`Gol de ${taker?.player.name||'pênalti'} de pênalti.`,{setPiece:'penalty',xG:.76});this.resetKickoff(defTeamIndex)}else this.changePossession(defTeamIndex,closest(team,this.state.ball))}else this.changePossession(1-defTeamIndex,attacker);this.stoppage('foul')}
 changePossession(teamIndex,player){if(this.state.possessionTeamIndex!==teamIndex){this.state.possessionTeamIndex=teamIndex;this.state.lastPossessionChangeAt=this.state.clockSeconds;this.state.teams[teamIndex].stats.recoveries++;if(player){player.stats.recoveries++;const l=localPoint(this.state.teams[teamIndex],player);if(l.x>.55)this.state.teams[teamIndex].stats.highRecoveries++}}attachBall(this.state.ball,player,teamIndex);this.state.activeAction=null;this.state.lastCompletedPass=null}
 stoppage(reason){this.state.stoppage={reason,at:this.state.clockSeconds};this.applyPendingChanges({halftime:false});this.state.stoppage=null}
 maybeManageAi(){const sec=Math.floor(this.state.clockSeconds);if(sec%20!==0)return;this.state.teams.forEach((team,ti)=>{if(!team.ai.enabled||this.state.clockSeconds-team.ai.lastDecisionAt<18)return;team.ai.lastDecisionAt=this.state.clockSeconds;const d=managerDecision(this.state,ti);this.state.analytics.insights[ti]=d.observation.evidence;if(d.tactics&&this.state.clockSeconds/60-team.ai.lastTacticalMinute>12){this.queueTactics(ti,d.tactics,{source:'ai'});team.ai.lastTacticalMinute=this.state.clockSeconds/60}if(d.sub&&this.state.clockSeconds/60-team.ai.lastSubMinute>9&&!team.pendingSubstitution){const incoming=team.bench.filter(p=>!team.usedPlayerIds.includes(String(p.id))).sort((a,b)=>(b.overall??b.rating)-(a.overall??a.rating))[0];if(incoming&&this.queueSubstitution(ti,d.sub.outgoingId,incoming.id,{source:'ai'}).ok)team.ai.lastSubMinute=this.state.clockSeconds/60}})}
 refreshDerived(){this.state.spatial.tactical=this.state.teams.map((_,i)=>tacticalShapeSnapshot(this.state,i));this.state.analytics.tactical=tacticalMetrics(this.state);this.state.analytics.insights=this.state.teams.map((_,i)=>observeMatch(this.state,i).evidence)}
 presentationSnapshot(){return {version:this.state.version,clockSeconds:this.state.clockSeconds,phase:this.state.phase,score:[...this.state.score],possessionTeamIndex:this.state.possessionTeamIndex,ball:{x:this.state.ball.x,y:this.state.ball.y,z:this.state.ball.z},teams:this.state.teams.map(t=>({direction:t.direction,players:t.players.filter(p=>!p.redCard).map(p=>({id:p.id,x:p.x,y:p.y,targetX:p.targetX,targetY:p.targetY,role:p.role,stamina:p.stamina}))}))}}
 periodBoundary(){if(this.state.phase==='firstHalf'){this.state.clockSeconds=HALF_SECONDS;this.state.phase='halftime';this.state.paused=true;this.clock.reset();this.addEvent('halftime',null,null,'Intervalo.');return}if(this.state.phase==='secondHalf'){this.state.clockSeconds=FULL_TIME_SECONDS;if(this.rules.extraTime&&this.state.score[0]===this.state.score[1]){this.state.phase='extraTimeBreak';this.state.paused=true;this.addEvent('extraTimeBreak',null,null,'Fim do tempo regulamentar. Haverá prorrogação.');return}return this.finishMatch()}if(this.state.phase==='extraTime')this.finishMatch()}
 finishMatch(){if(this.state.phase==='fulltime')return;this.state.phase='fulltime';this.state.paused=true;this.clock.reset();finalizeRatings(this.state);if(!this.rules.drawAllowed&&this.rules.penaltyShootout&&this.state.score[0]===this.state.score[1])this.resolvePenaltyShootout();this.addEvent('fulltime',null,null,'Fim de jogo.');this.refreshDerived();this.notify('fulltime')}
 resolvePenaltyShootout(){const kicks=[[],[]],goals=[0,0];let round=0;const takers=this.state.teams.map(t=>t.players.filter(p=>!p.redCard).sort((a,b)=>contextualSkill(b,['penalties','finishing','composure'])-contextualSkill(a,['penalties','finishing','composure'])));while(round<5||(goals[0]===goals[1]&&round<16)){for(let ti=0;ti<2;ti++){const p=takers[ti][round%takers[ti].length],gk=this.state.teams[1-ti].players.find(x=>x.role==='GK'&&!x.redCard),skill=contextualSkill(p,['penalties','finishing','composure']),keep=gk?contextualSkill(gk,['goalkeeping','reflexes','oneOnOne']):65,scored=this.rng.chance(clamp(.74+(skill-keep)/260,.55,.91));kicks[ti].push({playerId:p?.id||null,scored});if(scored)goals[ti]++}round++;if(round>=5&&goals[0]!==goals[1])break}this.state.shootout={goals,kicks,winnerTeamIndex:goals[0]>goals[1]?0:1};this.addEvent('penaltyShootout',this.state.shootout.winnerTeamIndex,null,`Disputa de pênaltis: ${goals[0]} × ${goals[1]}.`,{shootout:this.state.shootout});return this.state.shootout}
 checkInvariants(){const e=[];if(!Number.isFinite(this.state.clockSeconds)||this.state.clockSeconds<0)e.push('relógio inválido');if(this.state.score.some(x=>!Number.isInteger(x)||x<0))e.push('placar inválido');this.state.teams.forEach((t,i)=>{if(t.stats.passesCompleted>t.stats.passesAttempted)e.push(`passes equipe ${i}`);if(t.stats.shotsOnTarget>t.stats.shots)e.push(`chutes equipe ${i}`);if(t.substitutionsUsed>this.rules.maxSubstitutions)e.push(`subs equipe ${i}`);if(t.substitutionWindowsUsed>this.rules.maxSubstitutionWindows)e.push(`janelas equipe ${i}`);t.players.forEach(p=>{if(![p.x,p.y,p.stamina,p.stats.rating].every(Number.isFinite))e.push(`jogador ${p.id}`)})});return {ok:!e.length,errors:e}}
}
